name: Crash Report
description: The game crashes
title: "[Crash]: "
labels: ["crash", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: "# General Information"
  - type: textarea
    attributes:
      label: Description of the issue
      description: When did the crash occur? What where you doing?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Step for step instructions on how to reproduce the issue
      placeholder: "1.\n2.\n3.\n..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Environment"
  - type: input
    attributes:
      label: Mod version
      placeholder: eg. v1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      placeholder: eg. Windows 10
    validations:
      required: true
  - type: input
    attributes:
      label: Minecraft version
      placeholder: eg. 1.18.2
  - type: textarea
    attributes:
      label: Other mods
      description: Other mods that are required for reproduction and their version. \nPlease try to find a minimum test case that contains no mods that aren't required to reproduce the issue, you modpack isn't that specific.
      placeholder: "eg. Fabric API: 0.52.3 \nDumb Mod: 1.4.3"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Other Info"
  - type: dropdown
    attributes:
      label: Server
      description: Does the issue happen on dedicated servers?
      options:
        - Not tested
        - Happens
        - Doesn't happen
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Client
      description: Does the issue happen on the client side?
      options:
        - Not tested
        - Happens
        - Doesn't happen
    validations:
      required: true
  - type: input
    attributes:
      label: Logs
      description: The minecraft logs from when the issue was encountered. Please upload to pastebin or as a gist.
    validations:
      required: true
  - type: input
    attributes:
      label: Crash Report
      description: The crash report from when the issue was encountered. Please upload to pastebin or as a gist.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Extra Context
      description: Extra context for the bug. For example images, videos, related problems...