name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["release", "beta", "alpha"]
      minecraft-versions:
        description: Overrides for supported versions
        required: false
        type: string

jobs:
  publish:
    uses: MattiDragon/MattiDragon/.github/workflows/publish-mc-mod.yaml@8f1d197509b5119934fbc8f29cd3b25938d4b952
    with:
      version-type: ${{ inputs.version-type }}
      minecraft-versions: ${{ inputs.minecraft-versions }}
      modrinth-id: qlXnlZLG
      curseforge-id: 936929
      jitpack-safe-version: true
    secrets:
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
