name: Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: The type of release
        required: true
        type: choice
        options: ["release", "beta", "alpha"]
      minecraft-versions:
        description: Overrides for supported versions
        required: false
        type: string

jobs:
  publish:
    uses: MattiDragon/MattiDragon/.github/workflows/publish-mc-mod.yaml@8a736a4fde8c90e40f801aabc25b9254c1ed6b0d
    with:
      version-type: ${{ inputs.version-type }}
      minecraft-versions: ${{ inputs.minecraft-versions }}
#      modrinth-id: ""
#      curseforge-id: ""
      jitpack-safe-version: true
    secrets:
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
